config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :products, only: [] do
    resources :brands, module: :products, only: [:index]
  end
  resources :line_items
  resources :carts
  resources :instruments
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'instruments#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/instrument.rb
# frozen_string_literal: true

class Instrument < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  belongs_to :user, optional: true
  belongs_to :brand
  belongs_to :product
  has_many :line_items

  mount_uploader :image, ImageUploader
  serialize :image, JSON

  validates :title, :price, :model, presence: true
  validates :description, length: { maximum: 1000, too_long: '%{count} characters is the maximum allowed. ' }
  validates :title, length: { maximum: 150, too_long: '%{count} characters is the maximum allowed. ' }
  validates :price, numericality: { only_integer: true }, length: { maximum: 7 }

  BRAND = %w[AKG Audio-Technica Behringer Manley Neumann Oktava Shure].freeze
  TYPE = %w[Guitar Drums Keys Microphones Cases Cables Accessories].freeze

  private

  def not_referenced_by_any_line_item
    return if line_items.empty?

    errors.add(:base, 'Line items present')
    throw :abort
  end
end

app/controllers/instruments_controller.rb
# frozen_string_literal: true

class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :check_instrument_policy, only: %i[new edit create update destroy]

  # GET /instruments or /instruments.json
  def index
    @instruments = Instrument.all.order('created_at desc')
  end

  # GET /instruments/1 or /instruments/1.json
  def show; end

  # GET /instruments/new
  def new
    @instrument = current_user.instruments.build
  end

  # GET /instruments/1/edit
  def edit; end

  # POST /instruments or /instruments.json
  def create
    @instrument = InstrumentCreator.new(current_user, instrument_params).call
    if !@instrument.new_record?
      redirect_to @instrument, notice: 'Instrument was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /instruments/1 or /instruments/1.json
  def update
    if @instrument.update(instrument_params)
      redirect_to @instrument, notice: 'Instrument was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /instruments/1 or /instruments/1.json
  def destroy
    @instrument.destroy
    redirect_to instruments_url, notice: 'Instrument was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_instrument
    @instrument = Instrument.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def instrument_params
    params.require(:instrument).permit(:brand_id, :model, :description, :product_id, :title, :price, :image)
  end

  def check_instrument_policy
    redirect_to root_path, notice: "The user doesn't have permission to do it." unless InstrumentPolicy.new(current_user).access?
  end
end

app/helpers/instruments_helper.rb
# frozen_string_literal: true

module InstrumentsHelper
  def instrument_author(instrument)
    user_signed_in? && current_user.id == instrument.user_id
  end
end

app/views/instruments/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @instrument, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

      <div class="columns">

        <div class="field column is-9">
          <div class="control">
            <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field column">
          <div class="control">
            <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

      </div>

      <div class="field">
        <div class="control">
          <%= f.input :model, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
        </div>
      </div>

      <div class="columns">
        <div class="field column is-4">
          <div class="control">
            <label class="label">Brand</label>
            <div class="control has-icons-left">
                <span id="brand_select"></span>
            </div>
          </div>
        </div>

        <div class="field column is-4">
          <div class="control">
            <label class="label">Category</label>
            <div class="control has-icons-left">
                <span id="subcategory_select">
                  <%= f.collection_select :product_id, Product.order(:product_name), :id, :product_name, prompt: "Select type" %>
                </span>
            </div>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <label class="label">Add images</label>
          <div class="file">
            <label class="file-label">
              <%= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false %>
              <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
            </label>
          </div>
        </div>
      </div>
      <output id="list"></output>
      <hr />

      <div class="field is-grouped">
        <div class="control">
          <%= f.button :submit, class: 'button is-warning' %>
          <%= link_to 'Cancel', instruments_path, class:'button is-light' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/instruments/edit.html.erb
<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Editing Instrument
        </h1>
      </div>
    </div>
  </section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/index.html.erb
<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Browse the latest instruments on MyShop
        </h1>
      </div>
    </div>
  </section>
<% end %>

<div class="instrument-index-grid pt4">
  <% @instruments.each do |instrument| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
        <%= link_to image_tag(instrument.image_url(:thumb)), instrument %>
        <% if instrument.product.present? %>
          <div class="type">
            <span class="tag is-dark"><%= instrument.product.product_name %></span>
          </div>
        <% end %>
      </div>


      <div class="pa3">

        <h3 class="fw7 f4 title"><%= link_to instrument.title, instrument %></h3>

        <p class="has-text-gray fg pt1">Sold by <%= instrument.user.name %></p>

        <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(instrument.price) %></p>

        <% if instrument_author(instrument) %>
          <%= link_to 'Edit', edit_instrument_path(instrument), class: "button is-small" %>
          <%= link_to 'Delete', instrument, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
        <% end %>

      </div>
    </div>
  <% end %>
</div>

app/views/instruments/new.html.erb
<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Sell an Instrument
        </h1>
      </div>
    </div>
  </section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @instrument.title %></h1>

      <ul class="pv1">
        <% if @instrument.brand.present? %>
          <li class="inline-block pr3"><%= @instrument.brand.brand_name %></li>
        <% end %>

        <li class="inline-block pr3"><%= @instrument.model %></li>
      </ul>

      <div class="feature-image">
        <%= image_tag(@instrument.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

        <h3 class="subtitle is-4">Description</h3>
        <%= @instrument.description %>


        <h3 class="subtitle is-4 pt5">Product Specs</h3>

        <table class="table is-narrow">
          <% if @instrument.product.present? %>
            <tr>
              <td class="has-text-weight-bold">Type:</td>
              <td><%= @instrument.product.product_name %></td>
            </tr>
          <% end %>
          <% if @instrument.brand.present? %>
            <tr>
              <td class="has-text-weight-bold">Brand:</td>
              <td><%= @instrument.brand.brand_name %></td>
            </tr>
          <% end %>

          <tr>
            <td class="has-text-weight-bold">Model:</td>
            <td><%= @instrument.model %></td>
          </tr>
        </table>
      </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@instrument.price) %></h4>
        <p class="has-text-centered mb4">Sold by <%= @instrument.user.name %></p>
        <% unless instrument_author(@instrument) %>
          <%= button_to 'Add to cart', line_items_path(instrument_id: @instrument), class: 'button is-warning add-to-cart' %>
        <% end %>
      </div>
    </div>
  </div>

  <% if instrument_author(@instrument) %>
    <%= link_to 'Edit', edit_instrument_path(@instrument), class: 'button' %>
  <% end %>
</section>