config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :products, only: [] do
    resources :brands, module: :products, only: [:index]
  end
  resources :line_items
  resources :carts
  resources :instruments
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'instruments#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= yield (:body_class) %>">
<% if flash[:notice] %>
  <div class="notification is-success global-notification">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5">Shop</h1>
    <% end  %>
    <div class="navbar-burger burger" data-target="navbar">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbar" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">

          <% if total_cart_items %>
            <%= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
              <span>Cart
                <%= cart_count_over_one %>
                </span>
            <% end %>
          <% end %>

          <% if user_signed_in? %>
            <%= link_to 'Sell', new_instrument_path, class: "navbar-item button is-dark" %>

            <div class="navbar-item has-dropdown is-hoverable">
              <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
              <div class="navbar-dropdown is-right">
                <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
              </div>
            </div>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</nav>

<%= yield(:header) %>

<div class="container">

  <%= yield %>

</div>

</body>
</html>